@apiEndpoint = http://localhost:{{$dotenv PORT}}/api
@frontEndpoint = http://localhost:{{$dotenv PORT}}/

### 404 ✓
GET {{ frontEndpoint }}/nowayFor404

### 404 ✓
GET {{ apiEndpoint }}/nowayFor404

### Récupération de toutes les questions ✓
GET {{ apiEndpoint }}/question

### Récupération de la question 3 ✓
GET {{ apiEndpoint }}/question/3

### Récupération des questions du quiz 3 ✓
GET {{ apiEndpoint }}/question/quiz/3

### Création d'une question valide ✓
POST {{ apiEndpoint }}/question/
Content-Type: application/json

{
  "question_text": "Quel est le nom de Niko ?",
  "quiz_id": 1,
  "theme_id": 1
}

### Création d'une nouvelle question non valide (quiz_id is required) ✓
POST {{ apiEndpoint }}/question/
Content-Type: application/json

{
  "question_text": "Quel est le nom de Shaq ?",
  "theme_id": 1
}

### Modification de la question 35 ✓
PATCH {{ apiEndpoint }}/question/35
Content-Type: application/json

{
  "question_text": "Quel est le nom de Vinc Collet ?",
  "quiz_id": 1,
  "theme_id": 1
}

### Suppression d'un post ✓
DELETE {{ apiEndpoint }}/question/38


### Récupération de tous les quiz ✓
GET {{ apiEndpoint }}/quiz

### Récupération du quiz 3 ✓
GET {{ apiEndpoint }}/quiz/3

### Création d'un quiz ✓
POST {{ apiEndpoint }}/quiz/
Content-Type: application/json

{
  "quiz_name": "Quiz 999"
}

# ### Création d'une catégorie non valide
# POST {{ apiEndpoint }}/categories/
# Content-Type: application/json

# {
#   "route": "/$velte",
#   "label": "Svelte"
# }

### Modification d'un quiz ✓
PATCH {{ apiEndpoint }}/quiz/35
Content-Type: application/json

{
  "quiz_name": "Quiz 100" 
}

### Suppression d'un quiz ✓
DELETE {{ apiEndpoint }}/quiz/35